### ISSUE TITLE
difference in the TrainCode and TestCode

### ISSUE THREAD

**Issue by CVencode** [daitao/SAN#15]
Hello, thank you for your wonderful work .
As a beginner, I find that the TrainCode and TestCode are mostly similar, and  at first glance they look the same. Could you please tell me the main difference?

**Comment by Missdonghui** [comment]
Why is the PSNR value of my test calculated 0.
Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:10<00:00,  2.07s/it]
[MyImage x2]    PSNR: 0.000 (Best: 0.000 @epoch 1)
Total time: 10.34s, ave time: 2.07s
