### ISSUE TITLE
几个有关网络结构的问题

### ISSUE THREAD

**Issue by splinter21** [daitao/SAN#21]
1、看上去SOCA是一个很厉害的加强版CA，能否做一个将RCAN中所有CA换成SOCA的实验，这样可以证明SOCA比CA更强？
2、大组（SSRG）和小组（LSRAG）都是堆叠，但是结构略有区别，能否解释下为什么这样设计（为什么不同）吗？
（1）大组结尾有一个3x3卷积，而小组没有；
（2）小组结尾是SOCA，但是大组开头和结尾是RL-NL；
（3）大组用了对开头做残差，但是小组没有。
3、SSRG中的残差gamma，为什么是共享的同一个，而不是每一个小组用一个不同的gamma？
4、为什么SSRG前后的non-local是共享同一个，而不是用两个不同的？

**Comment by splinter21** [comment]
有关第一个问题，刚仔细看了一下，发现和RCAN的CA的位置是不一样的，RCAN是每个最小块的结尾，SAN是每个小组的结尾，那么如何决定，要在每多少个最小块后面放一个SOCA呢？每个最小块后面都放一个SOCA可行吗？

**Comment by splinter21** [comment]
5、non-local的inter_channel数是如何得到的，八分之一的输入channel数，那么是8。如果改变整个网络的通道数，那么应该维持八分之一的比例，还是维持8？

**Comment by splinter21** [comment]
6、看完代码又发现一个问题。。
self.conv_last
代码里LSRAG里用了conv，但是论文图里没有
论文图SSRG最后用了conv，但是代码里就在init里面写了一个self.conv_last，forward里面没有用到

**Comment by lookthatdog** [comment]
> 
> 
> 6、看完代码又发现一个问题。。
> self.conv_last
> 代码里LSRAG里用了conv，但是论文图里没有
> 论文图SSRG最后用了conv，但是代码里就在init里面写了一个self.conv_last，forward里面没有用到
老哥 你复现出来了吗 我现在也是这篇论文的代码出现了一些问题，首先他这个学习率的设计跟论文中不一样，论文里是每200次衰减一半，然后它代码里是每50代衰减为0.6，跑出来的X2的Set5效果为37.7,然后改为论文中的设置，跑出来的效果为37.981，后来我把LSRAG中的conv_last去掉，在SSRG中加入了conv_last，发现将LSRAG中最后一个卷积去掉的话效果会急剧变差，刚开始训练psnr值只有8点多，所以我又加上了这个卷积层然后又加上了SSRG中的那个卷积，但是目前感觉提升不是很明显。现在跑到1200代了还是37.974，离论文中的结果差别还是比较大

**Comment by splinter21** [comment]
> > 6、看完代码又发现一个问题。。
> > self.conv_last
> > 代码里LSRAG里用了conv，但是论文图里没有
> > 论文图SSRG最后用了conv，但是代码里就在init里面写了一个self.conv_last，forward里面没有用到
> > 老哥 你复现出来了吗 我现在也是这篇论文的代码出现了一些问题，首先他这个学习率的设计跟论文中不一样，论文里是每200次衰减一半，然后它代码里是每50代衰减为0.6，跑出来的X2的Set5效果为37.7,然后改为论文中的设置，跑出来的效果为37.981，后来我把LSRAG中的conv_last去掉，在SSRG中加入了conv_last，发现将LSRAG中最后一个卷积去掉的话效果会急剧变差，刚开始训练psnr值只有8点多，所以我又加上了这个卷积层然后又加上了SSRG中的那个卷积，但是目前感觉提升不是很明显。现在跑到1200代了还是37.974，离论文中的结果差别还是比较大

没复现，这么多问题，怎么跑，我就不浪费GPU了。。

**Comment by lookthatdog** [comment]
哇，老哥，可以加个好友吗？😂😂我都跑了一个星期了



---原始邮件---
发件人: "splinter21"<notifications@github.com&gt;
发送时间: 2019年12月20日(周五) 晚上6:15
收件人: "daitao/SAN"<SAN@noreply.github.com&gt;;
抄送: "lookthatdog"<512734333@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [daitao/SAN] 几个有关网络结构的问题 (#21)


  
6、看完代码又发现一个问题。。
 self.conv_last
 代码里LSRAG里用了conv，但是论文图里没有
 论文图SSRG最后用了conv，但是代码里就在init里面写了一个self.conv_last，forward里面没有用到
 老哥 你复现出来了吗 我现在也是这篇论文的代码出现了一些问题，首先他这个学习率的设计跟论文中不一样，论文里是每200次衰减一半，然后它代码里是每50代衰减为0.6，跑出来的X2的Set5效果为37.7,然后改为论文中的设置，跑出来的效果为37.981，后来我把LSRAG中的conv_last去掉，在SSRG中加入了conv_last，发现将LSRAG中最后一个卷积去掉的话效果会急剧变差，刚开始训练psnr值只有8点多，所以我又加上了这个卷积层然后又加上了SSRG中的那个卷积，但是目前感觉提升不是很明显。现在跑到1200代了还是37.974，离论文中的结果差别还是比较大
   
没复现，这么多问题，怎么跑，我就不浪费GPU了。。

**Comment by jilner** [comment]
SOCAmodule   中  论文用了残差，而程序中没有，只有y_cov*x    到底用那个呢

**Comment by lookthatdog** [comment]
我也不太清楚



---原始邮件---
发件人: "jilner"<notifications@github.com&gt;
发送时间: 2020年1月11日(周六) 中午12:17
收件人: "daitao/SAN"<SAN@noreply.github.com&gt;;
抄送: "lookthatdog"<512734333@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [daitao/SAN] 几个有关网络结构的问题 (#21)



SOCAmodule   中  论文用了残差，而程序中没有，只有y_cov*x    到底用那个呢

**Comment by lookthatdog** [comment]
我也不太清楚



---原始邮件---
发件人: "jilner"<notifications@github.com&gt;
发送时间: 2020年1月11日(周六) 中午12:17
收件人: "daitao/SAN"<SAN@noreply.github.com&gt;;
抄送: "lookthatdog"<512734333@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [daitao/SAN] 几个有关网络结构的问题 (#21)



SOCAmodule   中  论文用了残差，而程序中没有，只有y_cov*x    到底用那个呢
