### ISSUE TITLE
Attempting to Upscale 720p images, CUDA Out of Memory

### ISSUE THREAD

**Issue by nelaturuharsha** [daitao/SAN#31]
Hello,

Thank you so much for the excellent contribution! I am attempting to upscale a standard 720p image using SAN. I am using the 3x model, and have tried the following GPUs
1. 2060
2. 2x 2080Tis
3. Tesla V100

And the model is OOM (out of memory) in all of them. I'm actually at a loss, how should I proceed with regards to the same in order to run inference?

Thank you.

**Comment by Akshaypatil7** [comment]
Hi, did you solved this error?

**Comment by nelaturuharsha** [comment]
You can SR on patches and then stitch them together.
